---
name: Aleksander Dietrichson
position: "Chief Science Officer"
address: "Chi Square Laboratories"
phone: +54 (911) 6408 3613
email: "dietrichson@gmail.com"
github: dietrichson
linkedin: dietrichson
headcolor: 414141
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
```

```{r LoadData, include=FALSE}
education <- read.csv('./Dietrichson_education.csv')
professional_experience <- read.csv('./Dietrichson_professional.csv')
research_appointments <- 
  tribble(~title, ~dates, ~uni, ~loc, ~details,
  "Visiting Researcher","2003-2005","Keio University","Tokyo, Japan","Developed research-based curriculum for online courses in Academic English.",
  "Technology Fellow", "1999-2000", "Teachers College - Columbia University", "New York, NY", "Research on LMS and courseware usability."
)

```


# Education
```{r}
education%>% 
  detailed_entries(degree, dates, uni, loc, details)
```

# Research Appointments
```{r}
research_appointments %>% 
  detailed_entries(title, dates, uni, loc, details)
```

# Professional Experience
```{r}
professional_experience %>% 
 detailed_entries(role, dates, company, loc, details, .protect = FALSE)
```

# Publications

```{r}
bibliography_entries("./dietrichson_bibliography.bib")
```
# CRAN contributions

```{r}
bibliography_entries("./dietrichson_r_packages.bib")
```

