---
name: Aleksander Dietrichson
position: "Chief Data Scientist"
address: "X-Ray Research"
phone: +1 646 783 0620 / +54 (911) 6408 3613
email: "dietrichson@gmail.com"
github: dietrichson
linkedin: dietrichson
headcolor: 414141
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
```

```{r LoadData, include=FALSE}
education <- read.csv('./Dietrichson_education_spanish.csv')
professional_experience <- read.csv('./Dietrichson_professional_spanish.csv')
research_appointments <- 
  tribble(~title, ~dates, ~uni, ~loc, ~details,
  "Visiting Researcher","2003-2005","Keio University","Tokyo, Japan","Desarrollo de cursos online de inglés académico.",
  "Technology Fellow", "1999-2000", "Teachers College - Columbia University", "New York, NY", "Investigación de usabilidad de aulas virtuales y contenidos para cursos online."
)

```


# Educación
```{r}
education%>% 
  detailed_entries(degree, dates, uni, loc, details)
```

# Estancias y Cargos Académicos
```{r}
research_appointments %>% 
  detailed_entries(title, dates, uni, loc, details)
```

# Experiencia Profesional
```{r}
professional_experience %>% 
 detailed_entries(role, dates, company, loc, details, .protect = FALSE)
```

# Publicaciones

```{r}
bibliography_entries("./dietrichson_bibliography.bib", 
                     title="Selected Papers and Presentations",
                     sorting = "ydnt")
```

```{r}
bibliography_entries("./dietrichson_r_packages.bib", title="CRAN Contributions")
```

